### ISSUE TITLE
updateImpactSubmit fails with "Cannot find ivy report"

### ISSUE THREAD

**Issue by pawelkaczor** [updateimpact/updateimpact-sbt-plugin#1]
java.lang.IllegalStateException: Cannot find ivy report at [...]/root/target/resolution-cache/reports/root-root_2.10-compile.xml!
    at com.updateimpact.Plugin$$anonfun$1$$anonfun$2.apply(Plugin.scala:69)
    at com.updateimpact.Plugin$$anonfun$1$$anonfun$2.apply(Plugin.scala:64)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at com.updateimpact.Plugin$$anonfun$1.apply(Plugin.scala:64)
    at com.updateimpact.Plugin$$anonfun$1.apply(Plugin.scala:46)

**Comment by adamw** [comment]
Thanks for finiding that!
Is this module special in some way? Maybe some settings? Does it have any of the `target/resolution-cache/reports` directories? Are there any other reports (other than -compile)?

**Comment by adamw** [comment]
Version 1.0.10 of the plugin logs warnings instead of throwing exceptions. Would be great to know if this helped in your case.

**Comment by adamw** [comment]
(will be in maven central in ~15 minutes)

**Comment by pawelkaczor** [comment]
Problem solved :+1:
